### ISSUE TITLE
태그의 검색어와 그룹화 등이 정상적으로 작동이 되지 않는것 같습니다

### ISSUE THREAD

**Issue by dd1243** [Any-Material/nozomi-material#10]
![zoqcj](https://user-images.githubusercontent.com/85732785/123574333-979f3c80-d80a-11eb-9308-b97a8a3ff76b.PNG)

일전에 exclude검색어(-) 등을 사용해서 보고싶지 않은 태그의 갤러리를 걸러내고자 했지만,

원활히 작동되지 않았습니다
 
 
혹시나 해서 종합예시에 쓰여져있는 명령어를 그대로 옮겨왔는데

"한국어로 번역된 만화가 아닌 미검열 갤러리"를 연산하는게 아니라

"한국어로 번역되지 않은 만화가 아닌 미검열 갤러리"가 연산되었습니다
 
 
제가 검색어의 사용에 미숙함이 있었는지,

혹은 종합예시의 텍스트에 실수가 있었는지,

아니면 검색어 자체에 오류가 있었는지 궁금합니다
 
그리고 혹시나 제 실수였다면 보고싶지 않은 태그의 갤러리를 

어떻게 거를 수 있는지 궁금합니다
 
바쁘실텐데 이러한 일로 신경쓰이게 만들어서 죄송합니다

부디 조속히 검토해 주시길 바랍니다

그럼, 답변을 기다리겠습니다.

**Comment by Sombian** [comment]
다음 판올림서 다루도록 하겠습니다.
아울러 요즈음 일이 다소 바쁨과 더불어 현재 코드 전반을 再제작 하고 있는 까닭에 수정까지 시간이 상당히 경과될 것으로 예상갑니다. 감사합니다.

**Comment by dd1243** [comment]
빠른 답변 감사드립니다
서두르지 않으셔도 되니 컨디션에 지장이 가지 않게끔 조심해 주십시오
얼마가 걸리든 기다리겠습니다

**Comment by Sombian** [comment]
[1.1.4](https://github.com/Any-Material/nozomi-material/releases/tag/1.1.4) is just released, yet this time only #9 was addressed.
Sorry for inconvenience, and will surely look into this issue in later versions.
