### ISSUE TITLE
material의 작동이 안되는 것 같습니다+해결했습니다

### ISSUE THREAD

**Issue by dd1243** [Any-Material/nozomi-material#11]
![캡1처](https://user-images.githubusercontent.com/85732785/127644189-3a330d9e-e084-41aa-b4bc-39dbe254b303.PNG)
![캡2처](https://user-images.githubusercontent.com/85732785/127644197-58688f32-55fe-4105-9d49-563d74ce91f0.PNG)

여러모로 바쁘실텐데 귀찮게 해서 참 죄송합니다만 뷰어가 열리질 않습니다
사실 1.1.5 릴리즈 이전에도 이런 이슈가 있었지만 다음 버전에 뭔가 해결이 되겠지 싶었는데
릴리즈 이후에도 이런 문제가 있더군요

코드에 직접적인 버그가 없다면 제쪽에서 문제가 있을텐데
어떤 문제가 있는지 알아봐주신다면 참 감사하겠습니다

늘 수고하십니다

**Comment by dd1243** [comment]
앗 해결됬습니다
유니콘을 쓸땐 작동이 안됬는데 goodbyedpi를 쓰니 작동이 됩니다
괜히 신경쓰시게 만들어서 죄송합니다ㅠㅠ
유니콘 잘 됬었는데 왜 안되는지....

**Comment by Sombian** [comment]
작동이 된다니 다행입니다. 부담갖지 마시고 이상 있으시면 언제든지 issue 발행해주세요 ^^7

**Comment by Sombian** [comment]
추가 안내입니다. 앞으로는 통신사의 요청 차단을 정확하게 진단하기 위하여 xhr request 정보를 보내주시면 ctrl+shift+i 눌러서 첨부해주시면 감사하겠습니다.

**Comment by dd1243** [comment]
네 알겠습니다
선생님께 늘 신세지고 있습니다^^7
