### ISSUE TITLE
프로그램이 돌아가지 않습니다

### ISSUE THREAD

**Issue by yskrin** [Any-Material/nozomi-material#5]
![캡처](https://user-images.githubusercontent.com/37231665/118386842-4588ca00-b655-11eb-9c39-f7fb325db62e.JPG)
태그 치다가 실수로 두개 붙어서 써서 검색하니 저상태에서 40분째 그대로고 검색창에 아무것도 입력이 되지않습니다

**Comment by Sombian** [comment]
임지조치로 `config.json` 을 삭제하시면 정상작동 가능합니다.
해당 문제는 추후에 살펴보도록 하겠습니다.
즐거운 히토미 생활 하세요 ^^7

**Comment by yskrin** [comment]
해결됬습니다 감사합니다 ^^7

**Comment by Sombian** [comment]
fallback 추가 (`승인`)
