### ISSUE TITLE
프로그램을 실행하면 조작을 할 수 없습니다.

### ISSUE THREAD

**Issue by pewpewyoudie** [Any-Material/nozomi-material#6]
![12312123](https://user-images.githubusercontent.com/84761975/119442489-e9176000-bd62-11eb-882f-a0488a6d18c8.png)
안녕하세요. 1주전에도 위와 같은 문제로 인해 사용을 할 수 없었고 waifu 버전도 똑같이 아무런 반응이 없었습니다.
위에 검색창으로 보이는 칸에 마우스를 올리면 색상이 변하긴 하지만 클릭을 하면 아무런 변화가 없으며 키보드 입력 또한 먹히지 않습니다. 
 config.json을 삭제하고 실행하여도 마찬가지였으며 사용중이던 유니콘 HTTPS를 종료하고 실행하여도 똑같은 문제가 발생합니다.

언제나 ㅎㅌㅁ 유저를 위해 고생 많으십니다.

**Comment by pewpewyoudie** [comment]
방금 Hyper-v로 초기 상태의 윈도우에서 테스트를 해보았으나 똑같은 현상이 발생합니다.
혹시나 싶어서 일본 회선으로 접속을 해보니 정상적으로 작동하네요.. 아마도 SKB 특유의 해외 접속 장애가 원인인거 같습니다.
감사합니다.

**Comment by Sombian** [comment]
`Query` 의 활성화 조건은 `GalleryList` 의 `size` 가 0이 아닐경우입니다. 통상 `Query` 가 공백이라면 작동하는게 정상입니다만, 현제 외출중인 까닭에 금일 귀가후 살펴보겠습니다. 아울러 어제부터 6월 말까지 바쁜 일정이 잡혀 있는 연유로 주말에만 작업이 가능해 수정이 늦어질 수 있는점 양해바랍니다.

**Comment by Sombian** [comment]
#3 의 연장선으로, 답변 하셨듯이 회신 문제로 확인되었습니다.
저는 사용에 아무런 이상이 없네요.
(aishite material 은 회신이 끊겼을 때 안내문구를 넣을 수 있도록 고려중입니다.)
