### ISSUE TITLE
프로그램을 실행하면 조작할 수 없습니다

### ISSUE THREAD

**Issue by andrew21-1121** [Any-Material/nozomi-material#8]
실수로 nozomi-material을 먼저 실행하고 unicornhttps를 나중에 키면 컴퓨터를 재부팅하기 전까지 nozomi-material을 조작할 수 없습니다 또 unicornhttps를 꺼 놓은 상태로 컴퓨터를 오래 켜 놓다가 unicornhttps를 키고 프로그램을 실행하면 똑같은 문제가 발생합니다 재부팅하면 해결할 순 있지만 매번 재부팅하기 번거로워서 개선해 주셨으면 합니다

**Comment by Sombian** [comment]
해당 증상은 귀하가 사용중이신 기기의 독자적인 문제로 예상가며, 더불어 특정 ui 의 오류 따위와 다르게 networking 오류는 정확한 log 없이는 원인 파악에 어려움이 있는점 양해바랍니다.

**Comment by Sombian** [comment]
재차 확인후에 답변드립니다. 본 프로그램은 디스코드 외의 타 제품과 연동되는 부분이 전무함으로 해당 증상은 본전히 귀하가 사용중이신 장치의 독자적인 오류로서 nozomi-material 와 무관합니다.
