### ISSUE TITLE
이미지가 정상적으로 다운로드가 안됩니다

### ISSUE THREAD

**Issue by dd1243** [Any-Material/nozomi-material#9]
![화면 캡처 2021-06-11 164306](https://user-images.githubusercontent.com/85732785/121653763-00cb4400-cad8-11eb-8661-0c5aeb18d3d9.png)
몇몇 이미지들이 정상적으로 다운로드가 안 되고
이미지가 손상되었습니다
뷰어로도 이미지를 확인할 수 없고
용량도 정상적인 이미지파일보다 더 적습니다
(150b-165kb)

**Comment by Sombian** [comment]
진단 결과, 히토미라 사이트의 구조변경으로 인한 증상이며 신속히 수정하도록 하겠습니다.

**Comment by Sombian** [comment]
추출 논리 동기화 (`승인`)

**Comment by wasurname** [comment]
선생님 현재 똑같은 현상이 발생하고 있어서 그러는데, 혹시 확인 한 번 해주실 수 있으신가요?

**Comment by Sombian** [comment]
사이트가 논리를 바꾸는 주기가 짧아졌나 봅니다. 다음 판올림서 수정하도록 하겠습니다.

**Comment by Sombian** [comment]
Fixed as of [1.1.4](https://github.com/Any-Material/nozomi-material/releases/tag/1.1.4).

**Note**: [1.1.4](https://github.com/Any-Material/nozomi-material/releases/tag/1.1.4) made code evaulation possible, and to maximize the security, it only execute functions that are required.
